### ISSUE TITLE
metadata-indexer: zora.co og images not loading on mobile and desktop

### ISSUE THREAD

**Issue by ildi-x** [mod-protocol/mod#121]
Have been working on including support for Zora links: https://linkcaster.xyz/?page=1&filterUrl=zora.co&timestamp=latest&channel=global&reaction=

**Desktop:** some images are being blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. I have already added _crossorigin="anonymous"_ for Zora links as suggested by David here https://warpcast.com/df/0xf692e73b

Examples: 
https://zora.co/api/thumbnail/7777777/0xd04f3af1fa6be8ac65a43c679e8437d1113408f6/premint-4
https://zora.co/api/thumbnail/7777777/0x433bee782178d2e2cfc3325fd73b1ee60ad20808/premint-2
https://zora.co/api/thumbnail/7777777/0x34a4bd139aa8c17553f0ec3e8aeacc09f4bfb19f/premint-14

**Mobile:** most Zora og images are not loading. Two examples: 
https://warpcast.com/edurubio/0x3dd09056
https://warpcast.com/0xdesigner.eth/0x1327a041

![zora-error](https://github.com/mod-protocol/mod/assets/24465549/47ad674b-5ae5-4734-af5d-91389d9248dd)

**Comment by davidfurlong** [comment]
the examples images are working for me; do you have an example of an image url mod is giving you that is broken or missing when there should be one?

**Comment by ildi-x** [comment]
Two casts that the Mod indexer did not return images for: 

https://warpcast.com/al3xander/0xf3cf0108
https://warpcast.com/joehamilton/0x2eae325e

**Comment by davidfurlong** [comment]
yeah looks like something went wrong with the metadata of those casts
