### ISSUE TITLE
Miniapp icons need to respond to dark mode/different sizes

### ISSUE THREAD

**Issue by davidfurlong** [mod-protocol/mod#97]
Currently on dark mode, the Mini-app icons blend into the background. We should look at how other ecosystems deal with this - perhaps a `light` and `dark` property inside the image property? and different image sizes? (which)

**Comment by stephancill** [comment]
I dealt with this issue in opencast by adding a white background. Perhaps an option to consider

<img width="497" alt="Screenshot 2023-12-06 at 11 43 33" src="https://github.com/mod-protocol/mod/assets/5469870/08d59778-4389-4373-b087-e0b145ea4b1f">

**Comment by davidfurlong** [comment]
looks pretty good actually

**Comment by davidfurlong** [comment]
fixed
